name: tyamahori-simple-laravel-sutudy
x-common-settings: &healthcheck-settings
  interval: 1s
  timeout: 30s
  retries: 30
volumes:
  mysql:
  s3mock:
services:
  mysql:
    networks:
      default:
        aliases:
          - mysql.local
    image: mysql:9.5.0
    ports:
      - "127.0.0.1:3306:3360"
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
    healthcheck:
      test: [
        "CMD",
        "mysqladmin",
        "ping",
        "-h",
        "mysql.local",
        "-u",
        "sample",
        "-psample",
        "-P",
        "3306",
      ]
      <<: *healthcheck-settings

  mail:
    networks:
      default:
        aliases:
          - mail.local
    image: axllent/mailpit:v1.28.2
    ports:
      - "127.0.0.1:8025:8025"
    healthcheck:
      test: [
        "CMD",
        "ping",
        "-c",
        "3",
        "mail.local"
      ]
      <<: *healthcheck-settings

  storage:
    image: laravel-sutdy/s3mock:202601
    networks:
      default:
        aliases:
          - storage.local
          - sample.storage.local
    ports:
      - "127.0.0.1:9001:80" # 管理画面用ポート
      # - "9000:9000" # API用ポート
    environment:
      # ここでバケット名や認証情報を変更できます
      MINIO_ROOT_USER: "sample"
      MINIO_ROOT_PASSWORD: "samplesample"
      BUCKET_NAME: "sample"
      MINIO_DOMAIN: "storage.local"
    volumes:
      - type: volume
        source: s3mock
        target: /data

  php:
    networks:
      default:
        aliases:
          - php.local
    hostname: php
    image: laravel-sutdy/php:8.5
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - type: bind
        source: .
        target: /var/www/html
      - type: bind
        source: ./docker/mpm_prefork.conf
        target: /etc/apache2/mods-available/mpm_prefork.conf
      - type: bind
        source: ./docker/rd-default.conf
        target: /etc/apache2/sites-available/000-default.conf
      - type: bind
        source: ./docker/security.conf
        target: /etc/apache2/conf-available/security.conf
      - type: bind
        source: ./docker/php.ini
        target: /usr/local/etc/php/php.ini
      - type: bind
        source: ./docker/docker-php-ext-xdebug.ini
        target: /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    # .env.appをコンテナの環境変数に設定するようにしている。設定を変更する場合は、
    # 設定を変える場合は.env.appの内容を修正し、コンテナを再起動すること
    env_file: ./docker/.env.local
    depends_on:
      mysql:
        condition: service_healthy
      mail:
        condition: service_healthy
